# Generated by Django 3.2.9 on 2021-12-02 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_url', models.CharField(max_length=255)),
                ('page_site_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.site')),
            ],
        ),
    ]
