# Generated by Django 3.2.9 on 2022-05-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.TextField(db_column='type', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='request_datetime',
            field=models.DateTimeField(auto_now=True, db_column='datetime'),
        ),
    ]
