# Generated by Django 3.2.9 on 2021-12-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211202_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
