# Generated by Django 3.2.9 on 2021-12-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content_request_id',
            new_name='content_request',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='page_site_id',
            new_name='page_site',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='request_page_id',
            new_name='request_page',
        ),
    ]
