# Generated by Django 3.2.9 on 2021-12-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20211202_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content_request',
            new_name='request_id',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='page_site',
            new_name='site_id',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='request_page',
            new_name='page_id',
        ),
    ]
