# Generated by Django 3.2.9 on 2021-12-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211209_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='page_id',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
