# Generated by Django 3.2.9 on 2021-12-09 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20211209_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_url', models.CharField(max_length=255)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.site')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_html_content', models.CharField(max_length=255)),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.page')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_content', models.CharField(max_length=255)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.request')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
    ]
